[package]
name = "deflate"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fdeflate = "0.3.7"
flate2 = { version = "1.1.2", features = ["zlib-rs"] }
harness = { path = "../harness" }
libdeflater = "1.24.0"
miniz_oxide = "0.8.9"
zopfli = "0.8.2"
